#!/usr/bin/env node
var fs = require('fs')
const { checkAndPrintUsage } = require('./checkAndPrintUsage')

const args = process.argv.slice(2)
const settingsPath = "../iTerm2/com.googlecode.iterm2.plist"


const argToEditorTheme = {
  "azure": "257C710D-BE93-4B41-BF9D-52DA5A0C6FA1",
  "gr33n": "B91304B8-6CF5-460E-936B-7CA5C60C0318"
}

themeFromArgs = checkAndPrintUsage(argToEditorTheme, args[0])
if(! themeFromArgs){
  console.log("      Error in change-iterm2")
  console.log(`      Args given: ${args}`)
  return
} else {
  newEditorTheme = argToEditorTheme[themeFromArgs]
} 

fs.readFile(settingsPath, 'utf8', (err,data) => {
  if (err) {
    return console.log(err);
  }

  const result = data.replace(
    /\<string\>.*-.*-.*-.*-.*\<\/string\>\<!--DEFAULT_PROFILE--\>/g,
    `<string>${newEditorTheme}</string><!--DEFAULT_PROFILE-->`
  );

  fs.writeFile(settingsPath, result, 'utf8', (err) => {
     if (err) { 
       return console.log(err) 
     } else {
       console.log(`▶️   iTerm2 default profile changed to ${newEditorTheme}`)
     }
  });
});
