#!/usr/bin/env node
var fs = require("fs");
const { checkAndPrintUsage } = require("./checkAndPrintUsage");

const args = process.argv.slice(2);
const settingsPath = `${require('os').homedir()}/.config/nvim/init.vim`;

const argToEditorTheme = {
  azure: "midnightsun",
  gr33n: "gr33n",
  izzet: "izzet",
  backfire: "backfire",
  lux: "lux"
};

themeFromArgs = checkAndPrintUsage(argToEditorTheme, args[0]);
if (!themeFromArgs) {
  console.log("      Error in change-vim");
  console.log(`      Args given: ${args}`);
  return;
} else {
  newEditorTheme = argToEditorTheme[themeFromArgs];
}

fs.readFile(settingsPath, "utf8", (err, data) => {
  if (err) {
    return console.log(err);
  }

  const result = data.replace(
    /colorscheme .*/g,
    `colorscheme ${newEditorTheme}`
  );

  fs.writeFile(settingsPath, result, "utf8", err => {
    if (err) {
      return console.log(err);
    } else {
      console.log(`▶️   Neo Vim editor theme changed to ${newEditorTheme}`);
    }
  });
});

