#!/usr/bin/env node
var fs = require("fs");
const { checkAndPrintUsage } = require("./checkAndPrintUsage");

const args = process.argv.slice(2);
const settingsPath = `${require('os').homedir()}/.tmux.conf`;

const argToTmuxTheme = {
  azur3: "81",
  gr33n: "82",
  izz3t: "1",
  backfir3: "9",
  d3ng3ki: "11",
  gr3y: "15"
};

themeFromArgs = checkAndPrintUsage(argToTmuxTheme, args[0]);
if (!themeFromArgs) {
  console.log("      Error in change-tmux");
  console.log(`      Args given: ${args}`);
  return;
} else {
  newEditorTheme = argToTmuxTheme[themeFromArgs];
}

fs.readFile(settingsPath, "utf8", (err, data) => {
  if (err) {
    return console.log(err);
  }

  const result = data.replace(
    /set -g status-bg colour.*/g,
    `set -g status-bg colour${newEditorTheme}`
  ).replace(
    /set-option -g pane-active-border-style fg=colour.*/g,
    `set-option -g pane-active-border-style fg=colour${newEditorTheme}`
  )

  fs.writeFile(settingsPath, result, "utf8", err => {
    if (err) {
      return console.log(err);
    } else {
      console.log(`▶️   Tmux status bar changed to ${newEditorTheme}`);
    }
  });
});
