#!/usr/bin/env node
var fs = require("fs");
const { checkAndPrintUsage } = require("./checkAndPrintUsage");

const args = process.argv.slice(2);
const settingsPath =
  `${require('os').homedir()}/Library/Application Support/Code/User/settings.json`;

const argToEditorTheme = {
  azur3: "azure-theme",
  gr33n: "gr33n-theme",
  izz3t: "izzet-theme",
  backfir3: "backfire-theme",
  d3ng3ki: "lux-theme",
  gr3y: "gray-theme",
  lux: "lux-theme"
};

themeFromArgs = checkAndPrintUsage(argToEditorTheme, args[0]);
if (!themeFromArgs) {
  console.log("      Error in change-vscode");
  console.log(`      Args given: ${args}`);
  return;
} else {
  newEditorTheme = argToEditorTheme[themeFromArgs];
}

fs.readFile(settingsPath, "utf8", (err, data) => {
  if (err) {
    return console.log(err);
  }

  const result = data.replace(
    /"workbench.colorTheme": ".*"/g,
    `"workbench.colorTheme": "${newEditorTheme}"`
  );

  fs.writeFile(settingsPath, result, "utf8", err => {
    if (err) {
      return console.log(err);
    } else {
      console.log(`▶️   VSCode editor theme changed to ${newEditorTheme}`);
    }
  });
});
